apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 56.6.2
    helm:
      releaseName: monitoring
      values: |
        # --- START OF K3S FIXES ---
        # Tell Prometheus to stop looking for cloud-specific components
        kubeControllerManager:
          enabled: false
        kubeEtcd:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeProxy:
          enabled: false
        # Tell Prometheus to trust the K3s node certificates
        kubelet:
          enabled: true
          serviceMonitor:
            insecureSkipVerify: true
        # --- END OF K3S FIXES ---
        grafana:
          adminPassword: "admin"
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - grafana.home.local
            paths:
              - /
            pathType: Prefix
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true