apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api-deployment
  labels:
    app: python-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
      - name: python-api
        # IMPORTANT: Keep your custom image and tag here!
        image: walialakshay/python-gitops-app:e2942cc5ee78757523daa4b9540989a739eb6201
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: python-api-service
spec:
  selector:
    app: python-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  # We changed this to ClusterIP! It no longer gets a MetalLB address.
  type: ClusterIP 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-api-ingress
  annotations:
    ingressClassName: traefik
spec:
  rules:
  - host: python.home.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: python-api-service
            port:
              number: 80